### ISSUE TITLE
Avoid parsing inline equations in code blocks

### ISSUE THREAD

**Issue by bytesnake** [rust-ml/book#10]
At the moment this code snippets
```bash
user@computer:~/rust-ml/book$ cd code/
user@computer:~/rust-ml/book/code$ cargo run --release --example kmeans
```
is parsed with the dollar symbols as inline equations.

**Comment by quietlychris** [comment]
There's now a native option for MathJax support in `mdbook`, by adding `mathjax-support = true` under the `[output.html]` heading, which might be a fair alternative to using the `mdbook-scientific` package as a pre-processor. I've experimented around with it a little for the update I'm putting together for the first couple of chapters now that Lifna 0.6 has come out
