### ISSUE TITLE
Add content license for non-code portions

### ISSUE THREAD

**Issue by quietlychris** [rust-ml/book#4]
Per the Rust Embedded [Book](https://github.com/rust-embedded/book), it looks like it's common to include a license for the prose sections of a book as well. I believe that they use the CC-BY-SA 4.0 license, terms of which can be seen [here](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by bytesnake** [comment]
the CC license reads reasonable, the `ShareAlike` section reads a bit like a GPL license for prose, which I think is the way to go here. On my part we can double-license the code under MIT/Apache and the prose as CC-BY-SA 4.0

**Comment by quietlychris** [comment]
That sounds like a plan to me. I think in the long-term I'd like to keep an eye on some of the ethical license stuff I've mentioned in the past regarding code, but since most of that stuff is still somewhat under construction, I'm pretty happy with staying with MIT/Apache2.0 at the moment as well. CC-BY-SA 4.0 for the prose sounds fine to me either way. I'll plan to push those licenses in the next day or two

**Comment by quietlychris** [comment]
Resolved per commit 35f6125
